/*
 *  Copyright (c)  2021  Shabinder Singh
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.mousiki.shared.downloader.models.subtitles

import kotlin.jvm.JvmOverloads

class SubtitlesInfo @JvmOverloads constructor(
    url: String,
    val language: String,
    val isAutoGenerated: Boolean,
    val fromCaptions: Boolean = false
) {
    val url: String = url.replace(fmtRegex,"")  // existing format
        .replace(tlangRegex,"") // existing translation language

    val subtitles: Subtitles get() = Subtitles(url)

    override fun toString(): String {
        return "SubtitlesInfo($url,$language,$isAutoGenerated,$fromCaptions)"
    }

    companion object {
        private val fmtRegex = Regex("&fmt=[^&]*")
        private val tlangRegex = Regex("&tlang=[^&]*")
    }
}
