# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  lane :beta do
        gradle(
          task: "assemble",
          build_type: "DevRelease"
        )
        firebase_app_distribution(
            app: "1:905678518748:android:e3d3e565fa4b5c4125b719",
            groups: "qa-team",
            release_notes: "
            - Let user retry loading trending when error.
            "
        )
    end

    lane :betaMe do
            gradle(
              task: "assemble",
              build_type: "DevRelease"
            )
            firebase_app_distribution(
                app: "1:905678518748:android:e3d3e565fa4b5c4125b719",
                testers: "abdelhadibahddou@gmail.com",
                firebase_cli_path: "/Users/macbook/Firebase/firebase",
                release_notes: "
                - Recognize when app started from a dynamic link.
                - Bug fixes.
                "
            )
        end
end
