on:
  push:
    tags:
      - 'iOSFMK-*'
  workflow_dispatch:
    inputs:
      tag:
        description: iOS Framework version
        type: string
        required: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout framwork repository
        uses: actions/checkout@v2
        with:
          repository: yalive/MousikiSharedPod
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: iOS-framwork

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build iOS framework
        id: buildPackage
        run: |
          cd main
          ./gradlew createXCFramework

      - name: Copy swiftpackage to ios-framwork folder
        run: |
          cp -R ./main/shared/swiftpackage/shared.xcframework ./iOS-framwork/

      - name: Prepare FMK version
        id: get-tag
        run: |
          inputTag=${{ github.event.inputs.tag }}
          if [ "$inputTag" == "" ];then
             inputTag=$(echo ${{github.ref_name}} | cut -d- -f2)
          fi
          echo "::set-output name=tag::$inputTag"

      - name: Update podspec file version
        run: kotlin ./main/.github/scripts/PodspecUpdate.kts ${{ steps.get-tag.outputs.tag }}


      - name: Check FMK version
        run: |
          echo 'Tag that generate build is ${{ github.ref_name }}'
          echo 'FMK version ${{ steps.get-tag.outputs.tag }} will be pushed'

      - name: Push to iOS framwork repository
        run: |
          cd iOS-framwork
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Updated from Github actions"
          git tag ${{ steps.get-tag.outputs.tag }}
          git push origin main --tags