name: Upload beta version to firebase app distribution
on:
  push:
    branches:
      - develop
  pull_request:
jobs:
  Deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install Bundler Dependencies
        run: gem install bundler && bundle install

      - name: Run Fastlane Beta Lane
        run: fastlane beta
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}